### ISSUE TITLE
Question: Lines missing from 4.37 BWR

### ISSUE THREAD

**Issue by rei-vilo** [Hardy-PDi/ePaper_EXT2_Energia#8]
The iTC 4.20 BWR and iTC 4.37 BWR seem very similar. 

However, those lines present in the [iTC 4.20 BWR example](https://github.com/Hardy-PDi/ePaper_EXT2_Energia/blob/master/4.20_BWR/EPD420_energia.ino#L75) are not included in the [iTC 4.37 BWR example](https://github.com/Hardy-PDi/ePaper_EXT2_Energia/blob/master/4.37_BWR/EPD437_energia.ino).

https://github.com/Hardy-PDi/ePaper_EXT2_Energia/blob/deb61b7a6019fe4e716860c81a0a755bef586c56/4.20_BWR/EPD420_energia.ino#L75-L84

@Hardy-PDi Is there a technical reason for that? Thank you!

**Comment by Hardy-PDi** [comment]
Hi Olivier,

You can skip Line 75~84 of 4.2”. It’s for old model(E2417ES053).
At the very beginning, when we were developing our iTC EPD(1.54”~4.37”), we did not configure the parameters inside the EPD, hence we have to input Line 75~84.
Now, our latest COG can automatically load the proper parameters to the individual EPD, it help the user to minimize the initial step of programming.
And of course, we think the newest EPD is so-called backward compatible as long as the old model user can just simply eliminate a few line in their program.

**Comment by rei-vilo** [comment]
Thank you!
